name: flutter_svg
description: An SVG rendering and widget library for Flutter.
author: Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/flutter_svg
version: 0.1.1

dependencies:
  path_drawing: ^0.2.2
  xml: ^3.0.0
  vector_math: ^2.0.4
  meta: ^1.1.2
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  test: ^0.12.34
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flutter_logo.svg
    - assets/dart.svg
    - assets/w3samples/alphachannel.svg
    - assets/w3samples/aa.svg
    - assets/deborah_ufw/new-action-expander.svg
    - assets/deborah_ufw/new-camera.svg
    - assets/deborah_ufw/new-gif-button.svg
    - assets/deborah_ufw/new-gif.svg
    - assets/deborah_ufw/new-image.svg
    - assets/deborah_ufw/new-mention.svg
    - assets/deborah_ufw/new-pause-button.svg
    - assets/deborah_ufw/new-play-button.svg
    - assets/deborah_ufw/new-send-circle.svg
    - assets/deborah_ufw/numeric_25.svg
    - assets/simple/ellipse.svg
    - assets/simple/group_opacity.svg
    - assets/simple/nested_group.svg
    - assets/simple/rect_rrect.svg
    - assets/simple/linear_gradient.svg
    - assets/simple/linear_gradient_2.svg
    - assets/simple/radial_gradient.svg
    - assets/simple/dash_path.svg
    - assets/simple/text.svg
    - assets/simple/style_attr.svg
    - assets/wikimedia/Ghostscript_Tiger.svg
    - assets/android_vd/battery_charging.xml

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=0.3.6 <2.0.0"
